### ISSUE TITLE
没有配置成功

### ISSUE THREAD

**Issue by yulaughing** [TheOne1006/egg-swagger#2]
除了，介绍的配置，还需要其他的配置么？

**Comment by TheOne1006** [comment]
@yulaughing  你只使用 egg-swagger 这个库么, 代码方便发出来?

**Comment by yulaughing** [comment]
是的，仅仅使用了，egg-swagger。
然后，只配置了config文件，和plugin。文件。

**Comment by yulaughing** [comment]
// {app_root}/config/plugin.js
exports.swagger = {
  enable: true,
  package: 'egg-swagger',
};
Configuration
// {app_root}/config/config.default.js
exports.swagger = {
  enable: true,
  mountPath: '/test-mount', // swagger-ui  address  <domain>/test-mount
  swaggerFilePath: '/test-swagger.json', // swagger file default path
  enableGoogleFont: false,
};
按照这个配置的。
@TheOne1006

**Comment by TheOne1006** [comment]
那  swagger.json 需要自己写， 或者用其他 工具生成。 类似于 <https://egg-swagger-demo.herokuapp.com/swagger.json>,

**Comment by yulaughing** [comment]
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Simple API",
        "description": "A simple API to learn how to write OpenAPI Specification"
    },
    "schemes": [
        "https"
    ],
    "host": "simple.api",
    "basePath": "/openapi101",
    "paths": {
        "/persons": {
            "get": {
                "summary": "Gets some persons",
                "description": "Returns a list containing all persons.",
                "responses": {
                    "200": {
                        "description": "A list of Person",
                        "schema": {
                            "type": "array",
                            "items": {
                                "properties": {
                                    "firstName": {
                                        "type": "string"
                                    },
                                    "lastName": {
                                        "type": "string"
                                    },
                                    "username": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
这是swagger.json。还需要，在路由中，配置，egg-swagger么？

**Comment by yulaughing** [comment]
ok，json ,里面的确有个地方写错了。行的通了。谢谢
